template-file-path: template.yml
parameters:
  TargetGroupHealthCheckCodes: '200'
  TargetGroupHealthCheckPath: /health-path
  VpcId: vpc-0e0063f4338cdd0eb
  TargetGroupPort: '5000'
  SubnetIds: subnet-000a50eba179ba5d3,subnet-076e73e893c24ac69
tags: {}
