AWSTemplateFormatVersion: '2010-09-09'

Description: Professional Load Balancer Stack for ECS Deployment (Without HTTPS & ACM) with In-Place Updates and Compliant Naming

Parameters:
  TargetGroupPort:
    Type: Number
    Description: Port for the Target Group
    Default: 80

  TargetGroupHealthCheckPath:
    Type: String
    Description: Health check path for the Target Group
    Default: "/health"

  TargetGroupHealthCheckCodes:
    Type: String
    Description: Expected HTTP response codes for health checks (e.g., 200, 301)
    Default: "200"

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the Load Balancer will be created

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs for the Load Balancer

  EnableAccessLogs:
    Type: String
    Description: Enable S3 Access Logs for Load Balancer (true/false)
    AllowedValues: ["true", "false"]
    Default: "false"

Conditions:
  EnableS3Logging: !Equals [!Ref EnableAccessLogs, "true"]

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${AWS::StackName}-TG"
      Port: !Ref TargetGroupPort
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: !Ref TargetGroupHealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: !Ref TargetGroupHealthCheckCodes
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-TG"

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the Load Balancer allowing HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-SG"

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${AWS::StackName}-ALB"
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets: !Ref SubnetIds
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
        - Key: deletion_protection.enabled
          Value: 'true'
        - !If 
          - EnableS3Logging
          - Key: access_logs.s3.enabled
            Value: 'true'
          - !Ref AWS::NoValue
        - !If
          - EnableS3Logging
          - Key: access_logs.s3.bucket
            Value: !Ref AccessLogsBucket
          - !Ref AWS::NoValue
        - !If
          - EnableS3Logging
          - Key: access_logs.s3.prefix
            Value: "alb-logs"
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ALB"

  AccessLogsBucket:
    Type: AWS::S3::Bucket
    Condition: EnableS3Logging
    Properties:
      BucketName: !Sub "alb-logs-${AWS::StackName}-${AWS::AccountId}"
      ObjectOwnership: BucketOwnerEnforced
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-S3"

  AccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: EnableS3Logging
    Properties:
      Bucket: !Ref AccessLogsBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: "logdelivery.elasticloadbalancing.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${AccessLogsBucket}/*"

  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  LoadBalancerDNSName:
    Description: The DNS name of the Load Balancer
    Value: !GetAtt LoadBalancer.DNSName

  LoadBalancerArn:
    Description: The ARN of the Load Balancer
    Value: !Ref LoadBalancer

  TargetGroupArn:
    Description: The ARN of the Target Group
    Value: !Ref TargetGroup

  LoadBalancerSecurityGroupId:
    Description: The ID of the Load Balancer Security Group
    Value: !Ref LoadBalancerSecurityGroup
